% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Mar-2020 09:06:30
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('data2.mat');

K = 4;

M = [40 80 160 320];

N = [5 10 20 40];

epsilon_cell = saveVarsMat.epsilon_cell; % <4x1 cell> epsilon_cell{3,1} 中的元素太多

k = 1;

max_epsilon = [0.0010146388707870102; 6.5338723543639787E-5; 4.06245126338689E-6; ...
               2.5361067290674555E-7];

rate = [3.9568842554403703; 4.0075158601309768; 4.0016631393474533];

u0_cell = saveVarsMat.u0_cell; % <4x1 cell> u0_cell{3,1} 中的元素太多

u2 = ...
  [1 1 1 1;
   1 1 1 1;
   1 1 1 1;
   1 1 1 1];

u_cell = saveVarsMat.u_cell; % <4x1 cell> u_cell{3,1} 中的元素太多

x = [0.4 0.8 1.2 1.6];

x_cell = saveVarsMat.x_cell; % <4x1 cell> x_cell{3,1} 中的元素太多

y = 0.5;

y_cell = saveVarsMat.y_cell; % <4x1 cell> y_cell{3,1} 中的元素太多

clear saveVarsMat;
